### PR TITLE
add SPDX-License-Identifier headers

### LINKED ISSUE #95: Add SPDX-License-Identifier
ref: https://github.com/kgabis/parson/pull/121

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #95

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@giuseppe @cyphar @siretart PTAL?

**Comment by rhatdan** [comment]
LGTM

**Comment by siretart** [comment]
Lgtm

**Comment by AkihiroSuda** [comment]
@giuseppe LGTY?

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
