### PR TITLE
sync with qemu/qemu upstream

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Impact on package maintainers:
* New build dependency: `glib2-devel` (`libglib2.0-dev`)

Impact on contributors:
* Now `./qemu` directory is synced with `./qemu_patches/sync.sh`.
* The contents under `./qemu` must not be manually modified.
* The upstream commit of QEMU is specified in `./qemu_patches/sync.sh`.
* Patches under `./qemu_patches`:
  1. `slirp: add slirp_initx(SlirpConfig *, SlirpCb *, void *)`
  2. `slirp: allow custom MTU`
  3. `slirp: add disable_host_loopback (prohibit connections to 127.0.0.1)`

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@giuseppe PTAL. This PR is huge but changes under `qemu` directory can be mostly ignored, as it is just `vendor`-ed via `./qemu_patches/sync.sh`

cc @rootless-containers/slirp4netns-package-maintainers @elmarco FYI

**Comment by giuseppe** [comment]
LGTM, great work!

**Comment by AkihiroSuda** [comment]
Binary foot print (built on Ubuntu 18.04, dynamic, non-stripped)
* f30eaf1025798f95024291347a918316e4813745 (before): 646K
* ed0ef90c096deb2079d0529f3f69415e067e3352 (after): 838K

VSZ:RSS right after starting up slirp4netns
*  f30eaf1025798f95024291347a918316e4813745 (before): 4784:900 
* ed0ef90c096deb2079d0529f3f69415e067e3352 (after): 12616:2668

VSZ:RSS with max RSS during browsing random web sites using `w3m` 😛 
*  f30eaf1025798f95024291347a918316e4813745 (before): 6576:3288
* ed0ef90c096deb2079d0529f3f69415e067e3352 (after): 15368:4844

---

Wondering we should use https://github.com/mono/eglib instead of glib? (but eglib seems no longer maintained?)

**Comment by AkihiroSuda** [comment]
rebased with qemu/qemu@4c76137484878f42a2ce1ae1b888b6a7f66b4053

**Comment by AkihiroSuda** [comment]
Merging

**Pull request merged**
