### PR TITLE
sandbox: Warn if /etc/resolv.conf is a symlink to a file outside /etc or /run

### LINKED ISSUE #116: sandbox should be disabled when resolv.conf is a symlink to a file outside /etc or /run ?

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Close #116

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@giuseppe PTAL

**Comment by pcahyna** [comment]
This will not work if `/etc/resolv.conf` is a symlink to `/var/run/NetworkManager/resolv.conf` and `/var/run` is a symlink to `/run`. (`realpath(3)` returns only the final path, but here the problem is in the intermediate symlink in the symlink hieararchy.)

**Comment by AkihiroSuda** [comment]
Could you open an issue?

By "this will not work", do you just mean the warning isn't printed, or is something actually non-functional?

**Comment by pcahyna** [comment]
I mean, warning is not printed, and DNS resolving is non-functional (which is what the warning should warn about).

**Pull request merged**
