### PR TITLE
Don't leak memory when reallocation fails.

### PR DESCRIPTION
**Pull request by jnovy**
Signed-off-by: Jindrich Novy <jnovy@redhat.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but please submit the patch to the upstream? https://gitlab.freedesktop.org/slirp/libslirp

**Comment by jnovy** [comment]
Thanks. I'm not too familiar with gitlab and it refuses my commit:

remote: You are not allowed to push code to this project.
fatal: unable to access 'https://gitlab.freedesktop.org/slirp/libslirp.git/': The requested URL returned error: 403

Do I need to have any special privileges to allow me to do a PR against libslirp?

**Comment by AkihiroSuda** [comment]
* Create an account on https://gitlab.freedesktop.org/ (you can use gitlab.com credential and probably also github.com credential)
* Fork https://gitlab.freedesktop.org/slirp/libslirp.git/ as https://gitlab.freedesktop.org/YOUR_ACCOUNT/libslirp.git/
* Open MR from your fork, just as in opening GitHub PR from your fork

**Comment by jnovy** [comment]
https://gitlab.freedesktop.org/slirp/libslirp/merge_requests/13

Thanks Akihiro!

**Pull request closed without merging**
