### PR TITLE
tests: Avoid closing pipe by grep -q in cidr test

### PR DESCRIPTION
**Pull request by mbargull**

### CODE REVIEW

**Comment by mbargull** [comment]
Should we reinstate the `-o pipefail`?

**Comment by mbargull** [comment]
> Should we reinstate the `-o pipefail`?

I guess it doesn't hurt to have it in place, so I reverted the commit.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
nit: could you sign off commits (`git commit -s`)

**Comment by mbargull** [comment]
Oh, wait. The `-m1` might also close the pipe.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by mbargull** [comment]
Would you want me to squash these commits?

**Comment by AkihiroSuda** [comment]
Either is fine to me

**Pull request merged**
