### PR TITLE
[DNM] move --enable-{sandbox,seccomp} out of experimental

### LINKED ISSUE #177: Consider moving --enable-sandbox out of experimental
I'm planning to release v1.0.0 by the end of the month, and I'm considering moving `--enable-{sandbox,seccomp}` out of experimental.

@giuseppe @rhatdan WDYT?

**EDIT**: seccomp will stay experimental in v1.0.0 (https://github.com/rootless-containers/slirp4netns/issues/192)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #177

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
ping @giuseppe @rhatdan

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
BTW, I think enabling this also eliminate all 32 bit syscalls?

**Comment by AkihiroSuda** [comment]
Not sure, how to do that?

**Comment by rhatdan** [comment]
I believe once you enable it , then the 32 syscalls disappear, but @giuseppe would know better.

**Comment by AkihiroSuda** [comment]
If it is not clear, I think we can keep seccomp experimental

**Comment by AkihiroSuda** [comment]
@giuseppe WDYT?

**Comment by giuseppe** [comment]
that is true, by default only the native arch is added to the filter.

I don't think it will be an issue for us though, we shouldn't be using any 32 bit syscall as well as libslirp.

Now Podman uses `--enable-seccomp` if slirp4netns supports it, so we can see if it causes any issue: https://github.com/containers/libpod/pull/5624

**Comment by AkihiroSuda** [comment]
> I don't think it will be an issue for us though, we shouldn't be using any 32 bit syscall as well as libslirp.

Are we still vulnerable to ROP?

**Comment by AkihiroSuda** [comment]
sandbox will graduate experimental in v1.0.0 (https://github.com/rootless-containers/slirp4netns/pull/193), but seccomp will stay experimental (#192)

**Pull request closed without merging**
