### PR TITLE
experimental support for ipv6

### LINKED ISSUE #23: Add IPv6 support
As I can see in the source code, slirp4netns doesn't support IPv6.

Can you implement it?

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

Fix #23 @phantomcraft

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Now `ping6 fe80::2%tap0` works, but I don't have global IPv6 env here (OSS North America) and I'm not familiar with IPv6

**Comment by AkihiroSuda** [comment]
cc @giuseppe @cyphar

**Comment by giuseppe** [comment]
I've tried to wget a page from a container and it works well

**Comment by giuseppe** [comment]
should it be the default and have an option `-4 (ipv4 only)` to disable it?

**Comment by AkihiroSuda** [comment]
> I've tried to wget a webpage from a container and it works well

With `fe80::`? `fd00`? `fec0`? https://github.com/rootless-containers/slirp4netns/issues/23

> should it be the default and have an option -4 (ipv4 only) to disable it?

I'm wondering whether we can keep IPv6 support experimental, maybe until Kubernetes officially supports IPv6?

**Comment by AkihiroSuda** [comment]
> I'm wondering whether we can keep IPv6 support experimental,

especially for https://github.com/rootless-containers/rootlesskit/issues/14 and https://github.com/rootless-containers/slirp4netns/issues/11

I don't know what would make it difficult, but looks like the vdeplug_slirp maintainer faced some difficulty for supporting UDPv6: https://github.com/rd235/libslirp

**Comment by giuseppe** [comment]
> With fe80::? fd00? fec0? #23

this is what I've tried:

```
$ ip addr
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether ae:cf:31:2e:b9:33 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fe80::accf:31ff:fe2e:b933/64 scope link 
       valid_lft forever preferred_lft forever

$ wget -O/dev/null -6 "http://google.com"
--2018-09-03 10:12:13--  http://google.com/
Resolving google.com (google.com)... 2a00:1450:4014:801::200e
Connecting to google.com (google.com)|2a00:1450:4014:801::200e|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2018-09-03 10:12:13--  http://www.google.com/
Resolving www.google.com (www.google.com)... 2a00:1450:4001:80b::2004
Connecting to www.google.com (www.google.com)|2a00:1450:4001:80b::2004|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

/dev/null                                           [ <=>                                                                                                  ]  12.64K  --.-KB/s    in 0.03s   

2018-09-03 10:12:13 (448 KB/s) - ‘/dev/null’ saved [12943]
`

**Comment by giuseppe** [comment]
but I replace `fe80` with `fd00` then I have:

```
$ ip addr
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether d2:ba:cb:67:6f:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fd00::d0ba:cbff:fe67:6fa1/64 scope global dynamic mngtmpaddr 
       valid_lft 86372sec preferred_lft 14372sec
    inet6 fe80::d0ba:cbff:fe67:6fa1/64 scope link 
       valid_lft forever preferred_lft forever
$ wget  -O/dev/null  -6 "http://google.com"
--2018-09-03 10:16:14--  http://google.com/
Resolving google.com (google.com)... 2a00:1450:4014:801::200e
Connecting to google.com (google.com)|2a00:1450:4014:801::200e|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2018-09-03 10:16:14--  http://www.google.com/
Resolving www.google.com (www.google.com)... 2a00:1450:4001:80b::2004
Connecting to www.google.com (www.google.com)|2a00:1450:4001:80b::2004|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/null’

/dev/null                                           [ <=>                                                                                                  ]  12.67K  --.-KB/s    in 0.03s   

2018-09-03 10:16:15 (430 KB/s) - ‘/dev/null’ saved [12969]
```

so maybe it is better to use `fd00`

**Comment by AkihiroSuda** [comment]
Thanks for testing.
Still I haven't tested but I think this is mergeable now.

**Comment by giuseppe** [comment]
yes LGTM, I think we can merge it.

**Comment by aleks-mariusz** [comment]
sorry to bump an old issue but, i can't get `--enable-ipv6` working (i am using a patched podman 1.9 that was modified to include --enable-ipv6 to the slirp4netns call):

i get no reply pinging anything from within the container (nor can i ping the container link-local address from the host).. 

are there any other setup requirements to get this to work??

**Pull request merged**
