### PR TITLE
v1.1.7

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Flaky test:
```
============================================================================
Testsuite summary for slirp4netns 1.1.7+dev
============================================================================
# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/rootless-containers/slirp4netns/issues
============================================================================
make[4]: *** [Makefile:912: test-suite.log] Error 1
make[4]: Leaving directory '/slirp4netns/slirp4netns-1.1.7+dev/_build/sub'
make[3]: *** [Makefile:1020: check-TESTS] Error 2
make[3]: Leaving directory '/slirp4netns/slirp4netns-1.1.7+dev/_build/sub'
make[2]: *** [Makefile:1289: check-am] Error 2
make[2]: Leaving directory '/slirp4netns/slirp4netns-1.1.7+dev/_build/sub'
make[1]: *** [Makefile:1212: distcheck] Error 1
make[1]: Leaving directory '/slirp4netns'
=============================================
   slirp4netns 1.1.7+dev: ./test-suite.log
=============================================

# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/test-slirp4netns-cidr.sh
====================================

++ dirname ../../tests/test-slirp4netns-cidr.sh
+ . ../../tests/common.sh
+ child=2156
+ wait_for_network_namespace 2156
+ COUNTER=0
+ '[' 0 -lt 40 ']'
++ nsenter_flags 2156
++ pid=2156
++ flags=--target=2156
+ unshare -r -n sleep infinity
+++ readlink /proc/2156/ns/user
++ userns='user:[4026532557]'
+++ readlink /proc/2156/ns/mnt
++ mntns='mnt:[4026532212]'
+++ readlink /proc/2156/ns/net
++ netns='net:[4026532559]'
+++ readlink /proc/self/ns/user
++ self_userns='user:[4026531837]'
+++ readlink /proc/self/ns/mnt
++ self_mntns='mnt:[4026532212]'
+++ readlink /proc/self/ns/net
++ self_netns='net:[4026532217]'
++ '[' 'user:[4026532557]' '!=' 'user:[4026531837]' ']'
++ flags='--target=2156 --preserve-credentials -U'
++ '[' 'mnt:[4026532212]' '!=' 'mnt:[4026532212]' ']'
++ '[' 'net:[4026532559]' '!=' 'net:[4026532217]' ']'
++ flags='--target=2156 --preserve-credentials -U -n'
++ echo '--target=2156 --preserve-credentials -U -n'
+ flags='--target=2156 --preserve-credentials -U -n'
++ echo --target=2156 --preserve-credentials -U -n
++ grep -qvw -- -n
+ nsenter --target=2156 --preserve-credentials -U -n true
+ return 0
+ set +e
++ slirp4netns -c --cidr 24 2156 tun11
+ result='invalid CIDR: 24'
+ set -e
+ echo invalid CIDR: 24
+ grep 'invalid CIDR'
invalid CIDR: 24
+ set +e
++ slirp4netns -c --cidr foo 2156 tun11
+ result='invalid CIDR: foo'
+ set -e
+ echo invalid CIDR: foo
+ grep 'invalid CIDR'
invalid CIDR: foo
+ set +e
++ slirp4netns -c --cidr 10.0.2.0 2156 tun11
+ result='invalid CIDR: 10.0.2.0'
+ set -e
+ grep 'invalid CIDR'
+ echo invalid CIDR: 10.0.2.0
invalid CIDR: 10.0.2.0
+ set +e
++ slirp4netns -c --cidr 10.0.2.100/24 2156 tun11
+ result='CIDR needs to be a network address like 10.0.2.0/24, not like 10.0.2.100/24'
+ set -e
+ echo CIDR needs to be a network address like 10.0.2.0/24, not like 10.0.2.100/24
+ grep 'CIDR needs to be a network address like 10.0.2.0/24, not like 10.0.2.100/24'
CIDR needs to be a network address like 10.0.2.0/24, not like 10.0.2.100/24
+ set +e
++ slirp4netns -c --cidr 10.0.2.100/26 2156 tun11
+ result='prefix length needs to be 1-25'
+ set -e
+ grep 'prefix length needs to be 1-25'
+ echo prefix length needs to be 1-25
prefix length needs to be 1-25
+ slirp_pid=2191
+ wait_for_network_device 2156 tun11
+ COUNTER=0
+ '[' 0 -lt 40 ']'
++ nsenter_flags 2156
++ pid=2156
++ flags=--target=2156
+ slirp4netns -c 2156 --cidr 10.0.135.128/25 tun11
+++ readlink /proc/2156/ns/user
sent tapfd=5 for tun11
received tapfd=5
++ userns='user:[4026532557]'
+++ readlink /proc/2156/ns/mnt
++ mntns='mnt:[4026532212]'
+++ readlink /proc/2156/ns/net
++ netns='net:[4026532559]'
+++ readlink /proc/self/ns/user
++ self_userns='user:[4026531837]'
+++ readlink /proc/self/ns/mnt
++ self_mntns='mnt:[4026532212]'
+++ readlink /proc/self/ns/net
++ self_netns='net:[4026532217]'
++ '[' 'user:[4026532557]' '!=' 'user:[4026531837]' ']'
++ flags='--target=2156 --preserve-credentials -U'
++ '[' 'mnt:[4026532212]' '!=' 'mnt:[4026532212]' ']'
++ '[' 'net:[4026532559]' '!=' 'net:[4026532217]' ']'
++ flags='--target=2156 --preserve-credentials -U -n'
++ echo '--target=2156 --preserve-credentials -U -n'
+ nsenter --target=2156 --preserve-credentials -U -n ip addr show tun11
2: tun11: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 5a:4f:a7:02:7b:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.135.228/25 brd 10.0.135.255 scope global tun11
       valid_lft forever preferred_lft forever
    inet6 fe80::584f:a7ff:fe02:7b0f/64 scope link tentative 
       valid_lft forever preferred_lft forever
+ return 0
+ trap cleanup EXIT
++ nsenter --preserve-credentials -U -n --target=2156 ip a show dev tun11
+ result='2: tun11: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 5a:4f:a7:02:7b:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.135.228/25 brd 10.0.135.255 scope global tun11
       valid_lft forever preferred_lft forever
    inet6 fe80::584f:a7ff:fe02:7b0f/64 scope link tentative 
       valid_lft forever preferred_lft forever'
+ grep -qF 10.0.135.228
+ grep -om1 '^\s*inet .*/'
+ echo '2: tun11: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 5a:4f:a7:02:7b:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.135.228/25 brd 10.0.135.255 scope global tun11
       valid_lft forever preferred_lft forever
    inet6 fe80::584f:a7ff:fe02:7b0f/64 scope link tentative 
       valid_lft forever preferred_lft forever'
+ cleanup
+ kill -9 2156 2191
FAIL tests/test-slirp4netns-cidr.sh (exit status: 141)

make: *** [Makefile:1459: ci] Error 1
```

**Comment by mbargull** [comment]
```
++ nsenter --preserve-credentials -U -n --target=2156 ip a show dev tun11
+ result='2: tun11: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 5a:4f:a7:02:7b:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.135.228/25 brd 10.0.135.255 scope global tun11
       valid_lft forever preferred_lft forever
    inet6 fe80::584f:a7ff:fe02:7b0f/64 scope link tentative 
       valid_lft forever preferred_lft forever'
+ grep -qF 10.0.135.228
+ grep -om1 '^\s*inet .*/'
+ echo '2: tun11: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 5a:4f:a7:02:7b:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.135.228/25 brd 10.0.135.255 scope global tun11
       valid_lft forever preferred_lft forever
    inet6 fe80::584f:a7ff:fe02:7b0f/64 scope link tentative 
       valid_lft forever preferred_lft forever'
+ cleanup
+ kill -9 2156 2191
FAIL tests/test-slirp4netns-cidr.sh (exit status: 141)
```
^-- my bad! That can be fixed by removing the `-q` from `grep -qF 10.0.135.228`.

**Comment by AkihiroSuda** [comment]
Just removing `-o pipefail` seems to fix the issue: https://github.com/rootless-containers/slirp4netns/pull/241/commits/381adf013f3e381f9b420da58698cefb6c49fa33

Is `-q` really related?

**Comment by AkihiroSuda** [comment]
Ah, seems this one https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q

**Comment by mbargull** [comment]
Yes, the `pipefail` most likely happens because of the `grep -q` which closes the pipe immediately.

**Comment by mbargull** [comment]
Addressed in gh-243.

**Pull request merged**
