### PR TITLE
[RFC] README.md: add maintenance policy

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

@rootless-containers/slirp4netns-approvers @rootless-containers/slirp4netns-package-maintainers RFC

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

**Comment by cyphar** [comment]
I'm not sure we really need to have a separation between C and D. Aside from that, LGTM.

**Comment by AkihiroSuda** [comment]
I added D just because RHEL 8.0 is using an early version w/o official version tag and we cannot (or I don't like to) create a branch for that.

**Pull request merged**
