### PR TITLE
slirp4netns: include version in status output

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/rootless-containers/slirp4netns/issues/22

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by ansemjo** [comment]
I have created another patch: 740b3462fc2fa7d3aa185a4175fd7a107eb3cadf

That works from checked-out git repositories or archives created with `git archive` or by downloading from GitHub.

**Comment by giuseppe** [comment]
> I have created another patch: [740b346](https://github.com/rootless-containers/slirp4netns/commit/740b3462fc2fa7d3aa185a4175fd7a107eb3cadf)

I am fine with your version, just one comment inline, and @AkihiroSuda can pick the version he prefers and close the other PR :-)

**Comment by AkihiroSuda** [comment]
Thanks, I'm not familiar with gitattributes, but #35 seems better?

**Comment by giuseppe** [comment]
closing in favor of #35

**Pull request closed without merging**
