### PR TITLE
IPv6 forwarding and random CIDR

### PR DESCRIPTION
**Pull request by pfandl**
#259 
#253

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Seems to need rebasing with the current master

**Comment by AkihiroSuda** [comment]
Also, please consider squashing commits

**Comment by pfandl** [comment]
> Also, please consider squashing commits

I don't understand?

**Comment by AkihiroSuda** [comment]
https://www.git-tower.com/learn/git/faq/git-squash/

**Comment by pfandl** [comment]
@AkihiroSuda can i create another pull request from this branch? https://github.com/pfandl/slirp4netns/commit/9e226c2b48ee9f44a7b8d1e4673968d09bd35ec6

it should be just one commit containing all changes

**Comment by AkihiroSuda** [comment]
Yes, please

**Pull request closed without merging**
